// j_react/src/components/card.tsx
import { useState } from "react";
import { CardData, CardProps } from "../types/cardTypes";
import AddForm from "./addForm";
import { ITask } from "../types/taskType";

export default function Card({ cardData, cardStyle }: CardProps) {
  const [showForm, setShowForm] = useState(false);
  const [tasklist, setTask] = useState<ITask[]>([]);

  const getPriorityColor = (cardData: CardData): string => {
    return `card-header priority-${cardData.priority}`;
  };

  const toggleShowForm = () => {
    setShowForm(!showForm);
  };

  const handleSetTask = (newTask: ITask) => {
    setTask((prevTask) => [...prevTask, newTask]);
  };

  return (
    <div className="card m-1" style={{ width: cardStyle.width }}>
      <div className={getPriorityColor(cardData)}> {cardData.headerText}</div>

      <div className="card-body">
        <div className="d-flex justify-content-around">
          <h5 className="card-title">{cardData.title}</h5>

          <button className="btn btn-primary" onClick={toggleShowForm}>
            {showForm ? "Remove form" : "Add"}
          </button>
        </div>

        <hr />

        <p className="card-text">{cardData.description}</p>
      </div>

      {showForm && <AddForm setTask={handleSetTask} />}

      {tasklist && (
        <>
          <ul className="ul-list">
            {tasklist.map((task, index) => (
              <li key={index}> {task.taskname} </li>
            ))}
          </ul>
        </>
      )}
    </div>
  );
}

// j web/src/app/shared/components/card/card.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, signal } from '@angular/core';

import { ListItemComponent } from '../list-item/list-item.component';
import { FormComponent } from '../../../task/form/form.component';
import { ITask } from '../../model/task.model';
import { InputTaskComponent } from '../input-task/input-task.component';

@Component({
  selector: 'app-card',
  standalone: true,
  imports: [CommonModule, InputTaskComponent, ListItemComponent, FormComponent],
  templateUrl: './card.component.html',
  styleUrl: './card.component.scss',
})
export class CardComponent {
  @Input() headerText: string = '';
  @Input() height: string = '2rem';
  @Input() title: string = '';
  @Input() width: string = '19rem';
  @Input() cardData!: any;
  addNew = false;
  tasksSignal = signal<ITask[]>([]);

  add(taskData: ITask) {
    this.tasksSignal.update((tasks) => [...tasks, taskData]);
    this.addNew = false;
  }

  getPriorityColor() {
    return `priority-${this.cardData.priority}`;
  }
}

<div class="card m-1" [style.width]="width">
  <div *ngIf="headerText" class="card-header" [ngClass]="getPriorityColor()">
    {{ headerText }}
  </div>

  <div class="card-body">
    <div class="d-flex justify-content-between">
      <h5 class="card-title">{{ cardData.title }}</h5>

      @if (!addNew) {
      <button class="btn btn-primary" (click)="addNew = true">Add</button>
      } @else {
      <button class="btn btn-primary" (click)="addNew = false">
        Remove add form
      </button>
      }
    </div>

    <hr />
    <p class="description">{{ cardData.description }}</p>

    <app-list-item [tasks]="tasksSignal()"></app-list-item>

    @if (addNew) {
    <app-form (taskDataEvent)="add($event)"></app-form>
    }

    <ng-content></ng-content>
  </div>
</div>
